### ISSUE TITLE
编译失败,ExecutionException: org.gradle.api.GradleException: ABORT

### ISSUE THREAD

**Issue by iceAnson** [wurensen/gradle_plugin_android_aspectjx#20]
AGP:3.6.1
Gradle:6.3

* What went wrong:
Execution failed for task ':app:transformClassesWithAjxForZroTest64Debug'.
> java.util.concurrent.ExecutionException: org.gradle.api.GradleException: ABORT

**Comment by iceAnson** [comment]
/Users/ice/MeiyouCode/PeriodProject/SeeyouClient/app/build/intermediates/desugar_external_libs_classes/zroTest64Debug/out/83.jar:/Users/ice/MeiyouCode/PeriodProject/SeeyouClient/app/build/intermediates/desugar_external_libs_classes/zroTest64Debug/out/223.jar:/Users/ice/MeiyouCode/PeriodProject/SeeyouClient/app/build/intermediates/desugar_external_libs_classes/zroTest64Debug/out/237.jar:

        at org.aspectj.weaver.bcel.LazyClassGen.getJavaClassBytesIncludingReweavable(LazyClassGen.java:762)
        at org.aspectj.weaver.bcel.BcelWeaver.getClassFilesFor(BcelWeaver.java:1463)
        at org.aspectj.weaver.bcel.BcelWeaver.weaveAndNotify(BcelWeaver.java:1425)
        at org.aspectj.weaver.bcel.BcelWeaver.weave(BcelWeaver.java:1195)
        at org.aspectj.ajdt.internal.compiler.AjPipeliningCompilerAdapter.weaveQueuedEntries(AjPipeliningCompilerAdapter.java:514)
        at org.aspectj.ajdt.internal.compiler.AjPipeliningCompilerAdapter.afterCompiling(AjPipeliningCompilerAdapter.java:375)
        at org.aspectj.ajdt.internal.compiler.CompilerAdapter.ajc$afterReturning$org_aspectj_ajdt_internal_compiler_CompilerAdapter$2$f9cc9ca0(CompilerAdapter.java:69)
        at org.aspectj.org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:428)
        at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performCompilation(AjBuildManager.java:1107)
        at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performBuild(AjBuildManager.java:276)
        at org.aspectj.ajdt.internal.core.builder.AjBuildManager.batchBuild(AjBuildManager.java:189)
        at org.aspectj.ajdt.ajc.AjdtCommand.doCommand(AjdtCommand.java:114)
        at org.aspectj.ajdt.ajc.AjdtCommand.runCommand(AjdtCommand.java:60)
        at org.aspectj.tools.ajc.Main.run(Main.java:371)
        at sun.reflect.GeneratedMethodAccessor295.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSite.invoke(PojoMetaMethodSite.java:188)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135)
        at com.hujiang.gradle.plugin.android.aspectjx.internal.AJXTask.call(AJXTask.groovy:106)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

> Task :app:transformClassesWithAjxForZroTest64Debug FAILED
ajx[zroTest64Debug] transform start...
[ajx] close all open jar files: count=3307,cost=42ms
ajx[zroTest64Debug] incremental=false
:app:transformClassesWithAjxForZroTest64Debug spend 1941ms
      00:14.33   :app:processZroTest64DebugResources
      00:11.15   :app:compileZroTest64DebugRenderscript
      00:04.49   :app:desugarZroTest64Debug
      00:01.94   :app:transformClassesWithAjxForZroTest64Debug
      00:01.37   :app:compileZroTest64DebugJavaWithJavac
      00:01.05   :app:processZroTest64DebugManifest
      00:00.97   :app:clean
      00:00.84   :app:mergeZroTest64DebugResources
      00:00.46   :app:fixStackFramesZroTest64Debug
      00:00.45   :app:kaptGenerateStubsZroTest64DebugKotlin
      00:00.11   :app:compileZroTest64DebugKotlin
      00:00.10   :app:kaptZroTest64DebugKotlin

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithAjxForZroTest64Debug'.
> java.util.concurrent.ExecutionException: org.gradle.api.GradleException: ABORT

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 38s
19 actionable tasks: 5 executed, 14 from cache
[ice@icedeMacBook-Pro SeeyouClient (release-androidx=)]$

**Comment by wurensen** [comment]
@iceAnson 麻烦提供完整的错误日志，如果是aspectj织入错误，在build/outputs/logs目录下会有ajcore开头的日志文件

**Comment by Likeyong** [comment]
想问一下，这个问题解决了吗

**Comment by wurensen** [comment]
@Likeyong 请提供完整的异常信息，才能知道原因。

**Comment by Likeyong** [comment]
> @Likeyong 请提供完整的异常信息，才能知道原因。

是我没有排除一些class导致的
